version: "3.8"
services:
  db_game:
    image: postgres:14.4-alpine3.16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "7777:5432"
