version: "3.8"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server

  server:
    container_name: server
    image: krasnokutskiyea/sea-battle:latest
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db_game

  db_game:
    container_name: postgres
    image: postgres:14.4-alpine3.16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "7777:5432"
    volumes:
      - /var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
