version: "3.8"
services:

  client:
    container_name: client
    build: .
    ports:
      - "5000:5000"
    command: yarn start
    depends_on:
      - server

  server:
    container_name: server
    build: ./server
    volumes:
      - .:/app
    ports:
      - "8989:8989"
    command: yarn dev
    depends_on:
      - db_game

  db_game:
    container_name: postgres
    image: postgres:14.4-alpine3.16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "7777:5432"
    volumes:
      - /var/lib/postgresql/data
    restart: always
volumes:
  pgdata: