# This is a basic deploy to yandex-cloud

name: CI-CD

on:
  push:
    branches:
      - test-branch

jobs:
  push-docker-image:
    name: push docker-image to dockerhub 
    runs-on: ubuntu-latest
    
    steps:
      - name: Print hello 1
        run: echo "Hello world 1"

      - name: Print hello 2
        run: echo "Hello world 2"
        
      - name: checkout the repo
        uses: actions/checkout@v2
        
      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        
        
  

