# This is a basic deploy to yandex-cloud

name: CI-CD

on:
  push:
    branches: ["main", "test-branch"]

jobs:
  push-docker-image:
    name: push docker-image to dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo
        uses: actions/checkout@v2

      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: krasnokutskiyea/sea-battle:latest

      - name: execute remote ssh using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: cd app && sudo docker pull krasnokutskiyea/sea-battle:latest && sudo docker compose up -d && docker image prune -f






